[package]
name = "pnet_gdp_router"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet="0.30.0"

pnet_macros_support = "*"
pnet_macros = "*"
pnet_packet = "*"